bookaholic/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators = [DataRequired()])
    content = TextAreaField('Content', validators = [DataRequired()])
    submit = SubmitField("Post")

bookaholic/posts/routes.py
from flask import render_template,redirect,url_for, request, abort, flash, Blueprint
from flask_login import login_required, current_user
from bookaholic import db
from bookaholic.models import Post
from bookaholic.posts.forms import PostForm

pos = Blueprint('posts',__name__)


@pos.route("/posts")
def posts():
    page = request.args.get('page', 1 ,type = int)
    posts = Post.query.order_by(Post.date.desc()).paginate( page = page, per_page = 5)
    return render_template("posts.html", title = 'posts', posts= posts)

@pos.route("/post/new", methods = ['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title = form.title.data, content = form.content.data, author = current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created','success')
        return redirect(url_for('posts.posts'))
    return render_template('create_post.html', title = 'New_Post',form = form,legend = 'New Post' )

@pos.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("post.html", title = post, post = post)

@pos.route("/post/<int:post_id>/update", methods = ['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash ('Your post has been updated', 'success')
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title = 'Update_post',form = form, legend = 'Update Post')

@pos.route("/post/<int:post_id>/delete", methods = ['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post has been deleted','success')
    return redirect(url_for('posts.posts'))

bookaholic/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import login_required, logout_user, current_user, login_user
from bookaholic import db,bcrypt
from bookaholic.models import User, Post
from bookaholic.users.forms import RegistrationForm, LoginForm, UpdateAccountForm,ResetPassword, ResetForm
from bookaholic.users.utils import save_picture, send_reset_email

users = Blueprint('users',__name__)

@users.route("/login", methods = ['GET', 'POST'])
def login():
    #if user is logged in using the current_user method from flask_login
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        #check dataabase hashedpassword with the user form password
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user, form.remember.data)
            # if the user type from url  ,then capture that value after next and go to that url after the user logged in
            next_page = request.args.get('next')
            flash("You have logged in succesfully",'success')
            return redirect (next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Your username or password is incorrect ','danger')
    return  render_template('login.html', form = form, title='login')

@users.route("/register", methods = ['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        #stores values in user dv
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username = form.username.data, email = form.email.data, password = hashed_pw)
        db.session.add(user)
        db.session.commit()
        flash(f"Account created for {form.username.data} successfully",'success')
        return redirect(url_for('users.login'))

    return  render_template('register.html', form=form,title='register')

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@users.route("/account", methods = ['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data  
        db.session.commit()
        flash ('your account has been updated','success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename = 'profile_pics/' + current_user.image)
    return  render_template('account.html',title='account', image_file = image_file, form = form)

@users.route("/user/<string:username>", methods = ['GET', 'POST'])
def user_posts(username):
    page = request.args.get('page', 1 ,type = int)
    user = User.query.filter_by(username = username).first_or_404()
    posts = Post.query.filter_by(author = user)\
        .order_by(Post.date.desc())\
        .paginate( page = page, per_page = 5)
    return render_template("user_posts.html", title = 'posts', posts= posts, user = user)

@users.route("/reset_password", methods = ['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return render_template(url_for('main.index'))
    form = ResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_email(user)
        flash('An email has been send to reset your password')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',title = 'Reset Password', form = form)

@users.route("/reset_password/<token>", methods = ['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return render_template(url_for('main.index'))
    form = ResetForm()
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid Token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPassword()
    if form.validate_on_submit():
        #stores values in user dv
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()
        flash(f"Account password updated successfully",'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',form = form)

bookaholic/templates/account.html
{% extends 'layout.html' %}

{% block content %}
    <div class="form-container container">
        <div class="media">
            <img class="rounded-circle account-img" src='{{ image_file}}'>
            <div class="media-body">
                <h2 class="account-heading text-success">{{current_user.username}}</h2>
                <p class="text-secondary">{{current_user.email}}</p>
            </div>
            
                <div class="form-row mt-auto"><form method = 'POST', action = '' enctype="multipart/form-data">
                    {{form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom m text-white">Account Info</legend>
                        <div class="form-group text-white" >
                            {{form.username.label(class ='form-control-label text')}}
                            {% if form.username.errors%}
                                {{form.username(class ='form-control is-invalid')}}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                    <span>{{error}}</span>
                                    {% endfor%}
                                </div>
                            {%else%}      
                             {{form.username(class ='form-control')}} 
                            {% endif%}
                            
                        </div>
                        <div class="form-group text-white" >
                            {{form.email.label(class ='form-control-label')}}
                            {% if form.email.errors%}
                                {{form.email(class ='form-control is-invalid')}}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                    <span>{{error}}</span>
                                    {% endfor%}
                                </div>
                            {%else%}      
                             {{form.email(class ='form-control')}} 
                            {% endif%}
                            
                        </div>
                        <div class="form-group text-white" >
                            {{form.picture.label(class ='form-control-label')}}
                            {{form.picture(class='form-control-file ')}}
                            {% if form.picture.errors %}
                                {% for error in form.picture.errors %}
                                    <span class="text-danger">{{error}}</span></br>
                                {% endfor%}
                            {% endif %}
                            </div>
                        <div class="form-group mt-1">
                            {{form.submit(class=' btn btn-success')}}
                        </div>
                    </fieldset>
                </form>
            </div>
             
        </div>
    </div>
{% endblock %}

bookaholic/templates/create_post.html
{% extends 'layout.html' %}

{% block content %}
<div class = 'container form-container '>
    <div class="form-row mt-auto"><form method = 'POST', action = '' >
        {{form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom m text-white">{{legend}}</legend>
            <div class="form-group text-white" >
                {{form.title.label(class ='form-control-label')}}
                {% if form.title.errors%}
                    {{form.title(class ='form-control is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                        <span>{{error}}</span>
                        {% endfor%}
                    </div>
                {%else%}      
                 {{form.title(class ='form-control')}} 
                {% endif%}
                
            </div>
            <div class="form-group text-white" >
                {{form.content.label(class ='form-control-label')}}
                {% if form.content.errors%}
                    {{form.content(class ='form-control is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                        <span>{{error}}</span>
                        {% endfor%}
                    </div>
                {%else%}      
                 {{form.content(class ='form-control')}} 
                {% endif%}
            <div class="form-group mt-3">
                {{form.submit(class=' btn btn-success')}}
            </div>
        </fieldset>
       
    </form>
</div>
</div>
{% endblock %}

bookaholic/templates/index.html
{% extends 'layout.html' %}

{% block content %}
<form method="POST" action="">
  <section class="intro">
    <div class="bg-image h-100" >
      <div class="mask d-flex align-items-center h-100" style="background-color: rgba(61, 162, 195, 0.1);">
        <div class="container">
          <div class="card mask-custom p-4">
            <div class="card-body">
              <p class="h1 font-weight-bold mb-4 text-white">Search Your Favourite Books!</p>
              <div class="row justify-content-center">
                <div class="col-md-6 mb-3 mb-md-0">
                  <div id="basic" class="form-outline form-white">
                    <input type="text" id="form1" class="form-control form-control-lg" name="books" />
                    <label class="form-label text-white" for="form1">What are you looking for?</label>
                  </div>
                </div>
                <div class="col-md-2 ">
                  <input class="btn btn-success btn-lg" type="submit" value="Search" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</form>

{% endblock %} 

bookaholic/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel = 'stylesheet' type = 'text/css' href = '{{url_for("static", filename ='main.css')}}'>
    {% if title%}
    <title>bookaholic - {{ title }}</title>  
    {% else%}
    <title>bookaholic</title>
    {% endif %}
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-dark navbar-expand-lg bg">
    <a href ='/index' class="navbar-brand">BooKaholic</a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarmenu">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarmenu">
      {% if current_user.is_authenticated %}
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a href="{{url_for('posts.posts')}}" class="nav-link">POSTS</a> 
        </li>
        <li class="nav-item">
          <a href="{{url_for('posts.new_post')}}" class="nav-link">NEW POST</a> 
        </li>
        <li class="nav-item">
          <a href="{{url_for('users.logout')}}" class="nav-link">LOGOUT</a> 
        </li>
        <li class="nav-item">
          <a href="{{url_for('users.account')}}" class="nav-link">ACCOUNT</a> 
        </li>
      </ul>
     
      {% else %}
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a href="{{url_for('posts.posts')}}" class="nav-link">POSTS</a> 
        </li>
        <li class="nav-item">
          <a href="{{url_for('users.login')}}" class="nav-link">LOG IN</a> 
        </li>
        <li class="nav-item">
          <a href="{{ url_for('users.register') }}" class="nav-link">REGISTER</a> 
        </li>
      </ul>
      {% endif %}
      
    </div>
    
  </nav>
</div>
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category,message in messages%}
      <div class=" alert alert-{{category}}">{{message}}</div>
    {% endfor%}
  {% endif%}
{% endwith %}
      {% block content%} {% endblock%}
      
      
      <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
</body>
</html>

bookaholic/templates/login.html
{% extends 'layout.html' %}

{% block content %}

    <div class = 'container form-container '>
        <div class="form-row mt-auto"><form method = 'POST', action = '' >
            {{form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom m text-white">Log In</legend>
                <div class="form-group text-white" >
                    {{form.email.label(class ='form-control-label')}}
                    {% if form.email.errors%}
                        {{form.email(class ='form-control is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span>{{error}}</span>
                            {% endfor%}
                        </div>
                    {%else%}      
                     {{form.email(class ='form-control')}} 
                    {% endif%}
                    
                </div>
                <div class="form-group text-white" >
                    {{form.password.label(class ='form-control-label')}}
                    {% if form.password.errors%}
                        {{form.password(class ='form-control is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                            <span>{{error}}</span>
                            {% endfor%}
                        </div>
                    {%else%}      
                     {{form.password(class ='form-control')}} 
                    {% endif%}
                <small class='text-muted text-white'>
                    {{form.remember( class='form-check-input')}}
                    {{form.remember.label(class= 'form-check-label')}}
                </small>
                <div class="form-group ">
                    {{form.submit(class=' btn btn-success')}}
                </div>
                <small class="text-muted">Don't have an account ?<a class='text-decoration-none' href="url_for('main.index')">Sign up Here</a></small>
            </fieldset>
            <small class="text-muted"><a class='text-decoration-none 'href="{{url_for('users.reset_request')}}">Forgot your password?</a></small>
        </form>
    </div>
</div>
        
{% endblock %} 

bookaholic/templates/post.html
{% extends 'layout.html' %}

{% block content %}

<div class="container form-container mt-auto">
    <img class="rounded-circle " src ="{{url_for('static', filename = 'profile_pics/' + post.author.image)}}">   
            <a class="text-decoration-none text-success"href="{{url_for('users.user_posts', username = post.author.username)}}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date.strftime('%Y-%m-%d')}}</small>
            {% if post.author == current_user %}
                <div>
                    <a class="btn btn-secondary btn sm-1" href = "{{url_for('posts.update_post', post_id = post.id) }}">UPDATE</a>
                    <button type = 'button' class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">DELETE</button>
                </div>
            {% endif %}
            <h2 class ='text-white'>{{ post.title }}</h2>
          <div class="container form-container mt-auto"> <p class="text-white pb-1 ">{{ post.content }}</p></div>   
</div>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post ?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{url_for('posts.delete_post', post_id = post.id)}}" method = 'POST'>
               <input class="btn btn-danger" type = 'submit' value = 'Delete'>
          </form>
        </div>
      </div>
    </div>
  </div>
        
{% endblock %}

bookaholic/templates/posts.html
{% extends 'layout.html' %}

{% block content %}
{% for post in posts.items %}

<div class="container form-container mt-auto">
    <img class="rounded-circle " src ="{{url_for('static', filename = 'profile_pics/' + post.author.image)}}">   
            <a class="text-decoration-none text-success"href="{{url_for('users.user_post', username = post.author.username)}}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date.strftime('%Y-%m-%d')}}</small>
            <h2><a class="nav-link text-info mb-1" href="{{url_for('posts.post', post_id = post.id)}}">{{ post.title }}</a></h2>
          <div class="container form-container mt-auto"> <p class="text-white pb-1 ">{{ post.content }}</p></div>   
</div>     
{% endfor %}
{% for page_num in posts.iter_pages(left_edge =1, left_current = 1,right_edge = 1,right_current = 2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
      <a class=' mr-2 btn btn-success' href="{{url_for('posts.posts', page = page_num)}}">{{page_num}}</a>
    {% else%}
    <a class=' mr-2 btn btn-outline-success' href="{{url_for('posts.posts', page = page_num)}}">{{page_num}}</a>
    {% endif %}
  {% else %}

  {% endif %}
{% endfor %}

{% endblock %}

bookaholic/templates/register.html
{% extends 'layout.html' %}

{% block content %}
<div class = 'container form-container '>
    <div class="form-row mt-auto"><form method = 'POST', action = '' >
        {{form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom m text-white">Register</legend>
            <div class="form-group text-white" >
                {{form.username.label(class ='form-control-label')}}
                {% if form.username.errors%}
                    {{form.username(class ='form-control is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                        <span>{{error}}</span>
                        {% endfor%}
                    </div>
                {%else%}      
                 {{form.username(class ='form-control')}} 
                {% endif%}
                
            </div>
            <div class="form-group text-white" >
                {{form.email.label(class ='form-control-label')}}
                {% if form.email.errors%}
                    {{form.email(class ='form-control is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{error}}</span>
                        {% endfor%}
                    </div>
                {%else%}      
                 {{form.email(class ='form-control')}} 
                {% endif%}
                
            </div>
            <div class="form-group text-white" >
                {{form.password.label(class ='form-control-label')}}
                {% if form.password.errors%}
                    {{form.password(class ='form-control is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{error}}</span>
                        {% endfor%}
                    </div>
                {%else%}      
                 {{form.password(class ='form-control')}} 
                {% endif%}
            </div>
            <div class="form-group text-white" >
                {{form.confirm_password.label(class ='form-control-label')}}
                {% if form.confirm_password.errors%}
                    {{form.confirm_password(class ='form-control is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                        <span>{{error}}</span>
                        {% endfor%}
                    </div>
                {%else%}      
                 {{form.confirm_password(class ='form-control')}} 
                {% endif%}
            </div>
            <div class="form-group ">
                {{form.submit(class=' btn btn-success')}}
            </div>
            <small class="text-muted">Already have an account?<a class='text-decoration-none' href="url_for('main.index')">Login in</a></small>
        </fieldset>
    </form>
</div>
</div>
{% endblock %}

bookaholic/templates/reset_request.html
{% extends 'layout.html' %}

{% block content %}

    <div class = 'container form-container '>
        <div class="form-row mt-auto"><form method = 'POST', action = '' >
            {{form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom m text-white">Reset Password</legend>
                <div class="form-group text-white" >
                    {{form.email.label(class ='form-control-label')}}
                    {% if form.email.errors%}
                        {{form.email(class ='form-control is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span>{{error}}</span>
                            {% endfor%}
                        </div>
                    {%else%}      
                     {{form.email(class ='form-control')}} 
                    {% endif%}
                    
                </div>
                <div class="form-group ">
                    {{form.submit(class=' btn btn-success')}}
                </div>
            </fieldset>
        </form>
    </div>
</div>
        
{% endblock %} 

bookaholic/templates/reset_token.html
{% extends 'layout.html' %}

{% block content %}

    <div class = 'container form-container '>
        <div class="form-row mt-auto"><form method = 'POST', action = '' >
            {{form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom m text-white">Reset Password</legend>
                <div class="form-group text-white" >
                    {{form.password.label(class ='form-control-label')}}
                    {% if form.password.errors%}
                        {{form.password(class ='form-control is-invalid')}}
                        <div class="invalid-feedback">
                            {% for password in form.password.errors %}
                            <span>{{password}}</span>
                            {% endfor%}
                        </div>
                    {%else%}      
                     {{form.password(class ='form-control')}} 
                    {% endif%}
                    
                </div>
                <div class="form-group text-white" >
                    {{form.confirm_password.label(class ='form-control-label')}}
                    {% if form.confirm_password.errors%}
                        {{form.confirm_password(class ='form-control is-invalid')}}
                        <div class="invalid-feedback">
                            {% for password in form.confirm_password.errors %}
                            <span>{{password}}</span>
                            {% endfor%}
                        </div>
                    {%else%}      
                     {{form.confirm_password(class ='form-control')}} 
                    {% endif%}
                    
                </div>
                <div class="form-group ">
                    {{form.submit(class=' btn btn-success')}}
                </div>
            </fieldset>
        </form>
    </div>
</div>
        
{% endblock %} 

bookaholic/templates/search.html
{% extends 'layout.html' %}

{% block content %}

{% for book in books['items'] %}
<div class="container form-container mt-auto">
    {% if book.volumeInfo.imageLinks %}
    <img class='rounded-circle' src="{{book.volumeInfo.imageLinks.smallThumbnail}}">
    {% else %}
    <img class="rounded-circle" src = '../static/images/default_book.png'>
    {% endif %}
    {% if book.volumeInfo %}
    <a class=" text-decoration-none text-success"href="{{book.volumeInfo.previewLink}}" target="_blank">{{ book.volumeInfo.title}}</a>
    <!-- <small class=" text-muted text-decoration-none text-white "href="{{book.volumeInfo.previewLink}}" target="_blank">{{ book.volumeInfo.authors}}</small> -->
    {% else %}
    <a class="text-decoration-none text-success" href="" target="_blank">{{book.volumeInfo}}</a>
    {% endif %}
    <p class="text-white">{{book.volumeInfo.description}}</p>
</div>
{% endfor %}
{% endblock %}

bookaholic/templates/user_posts.html
{% extends 'layout.html' %}

{% block content %}
`   <h1 class="container text-white">Posts by {{user.username}} -[{{posts.total}}]</h1>
{% for post in posts.items %}

<div class="container form-container mt-auto">
    <img class="rounded-circle " src ="{{url_for('static', filename = 'profile_pics/' + post.author.image)}}">   
            <a class="text-decoration-none text-success"href="{{url_for('posts.user_post', username = post.author.username)}}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date.strftime('%Y-%m-%d')}}</small>
            <h2><a class="nav-link text-info mb-1" href="{{url_for('posts.post', post_id = post.id)}}">{{ post.title }}</a></h2>
          <div class="container form-container mt-auto"> <p class="text-white pb-1 ">{{ post.content }}</p></div>   
</div>      
{% endfor %}
{% for page_num in posts.iter_pages(left_edge =1, left_current = 1,right_edge = 1,right_current = 2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
      <a class=' mr-2 btn btn-success' href="{{url_for('users.user_post', username = user.username,page = page_num)}}">{{page_num}}</a>
    {% else%}
    <a class=' mr-2 btn btn-outline-success' href="{{url_for('posts.posts', username = user.username, page = page_num)}}">{{page_num}}</a>
    {% endif %}
  {% else %}

  {% endif %}
{% endfor %}

{% endblock %}